/*
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractSMRLScopeProvider extends XbaseBatchScopeProvider {
}
