/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.ide;

import lu.svv.lang.ide.AbstractSMRLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SMRLIdeModule extends AbstractSMRLIdeModule {
}
