/*
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.ide

import com.google.inject.Guice
import lu.svv.lang.SMRLRuntimeModule
import lu.svv.lang.SMRLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SMRLIdeSetup extends SMRLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SMRLRuntimeModule, new SMRLIdeModule))
	}
	
}
