/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.serializer;

import lu.svv.lang.serializer.AbstractSMRLSemanticSequencer;

@SuppressWarnings("all")
public class SMRLSemanticSequencer extends AbstractSMRLSemanticSequencer {
}
