/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.serializer;

import lu.svv.lang.serializer.AbstractSMRLSyntacticSequencer;

@SuppressWarnings("all")
public class SMRLSyntacticSequencer extends AbstractSMRLSyntacticSequencer {
}
