/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang;

import lu.svv.lang.AbstractSMRLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SMRLRuntimeModule extends AbstractSMRLRuntimeModule {
	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
		return SMRLJvmModelGenerator.class;
	}
}
