/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang;

import lu.svv.lang.SMRLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SMRLStandaloneSetup extends SMRLStandaloneSetupGenerated {
  public static void doSetup() {
    new SMRLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
