/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.sMRL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lu.svv.lang.sMRL.SMRLPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
} // Feature
