/*
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import lu.svv.lang.sMRL.SMRL

@ExtendWith(InjectionExtension)
@InjectWith(SMRLInjectorProvider)
class SMRLParsingTest {
	@Inject
	ParseHelper<SMRL> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			import static lu.svv.mr.language.Operations.*
			import lu.svv.mr.language.Action;
			
			package lu.svv.mr.owasp {
			  MR OTG_AUTHZ_002 {
			   {
			     for ( Action action : Input(1).actions() ){
				   IMPLIES(
				     cannotReachThroughGUI ( User(2), action.url ) &&
				     equal( Input(2), changeCredentials(Input(1), User(2)) )
					 ,
					 NOT( Output(Input(1)).equals(Output(Input(2)))));
			     }
			   } 
			}}
		''')
		println(result);
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
