/*
 * generated by Xtext 2.16.0
 */
package lu.svv.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SMRLStandaloneSetup extends SMRLStandaloneSetupGenerated {

	def static void doSetup() {
		new SMRLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
