/*
 * generated by Xtext 2.16.0
 */
package lu.svv.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SMRLRuntimeModule extends AbstractSMRLRuntimeModule {
	
	
}
