/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.validation;

import lu.svv.lang.validation.AbstractSMRLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SMRLValidator extends AbstractSMRLValidator {
}
