/*
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.parser.antlr;

import com.google.inject.Inject;
import lu.svv.lang.parser.antlr.internal.InternalSMRLParser;
import lu.svv.lang.services.SMRLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SMRLParser extends AbstractAntlrParser {

	@Inject
	private SMRLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSMRLParser createParser(XtextTokenStream stream) {
		return new InternalSMRLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SMRL";
	}

	public SMRLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SMRLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
