/*
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SMRLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("lu/svv/lang/parser/antlr/internal/InternalSMRL.tokens");
	}
}
