/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.ui;

import lu.svv.lang.ui.AbstractSMRLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SMRLUiModule extends AbstractSMRLUiModule {
  public SMRLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
