/**
 * generated by Xtext 2.16.0
 */
package lu.svv.lang.ui.contentassist;

import lu.svv.lang.ui.contentassist.AbstractSMRLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SMRLProposalProvider extends AbstractSMRLProposalProvider {
}
